# -----------------
# 企业信息 corp info
# -----------------

corp:
  name: 宽恒
  nameEnglish: Kuanheng
  nameFull: 宽恒网络技术有限公司
  about: 关于宽恒
  serices: 宽恒服务
  products: 宽恒产品
  samples: 成功案例

# -----------------
# 导航栏 navbar
# -----------------

nav:
  banner:
    - 
      banner: /images/banner-01.jpg
      slogan: VR解决方案
      description: 填写你需要的简介
    - 
      banner: /images/banner-02.jpg
      slogan: IDC机房
      description: 填写你需要的简介内容
    - 
      banner: /images/banner-03.jpg
      slogan: 系统集成
      description: 填写你需要的简介内容目标
    -
      banner: /images/banner-04.jpg
      slogan: 办公室设备
      description: 这里放置简介

# -----------------
# 菜单 menu
# -----------------

menu:
 首页: /
 关于宽恒: /about
 产品库: /product
 解决方案: /solution
 成功案例: /case
 企业动态: /update

tele: 400-008-0408

# -----------------
# 简要介绍 mini description
# -----------------


# -----------------
# 板式设定 layout
# -----------------

layout:
  about:
    name: about
  solution:
    name: solution
  case:
    name: case
  update:
    name: update
  product:
    name: product
# -----------------
# 主页内容 index content
# -----------------

index:
  # 服务
  services:
    -
      image: ./images/banner-01.jpg
      name: VR行业解决方案
      description: 针对各行业业务特性形成的AR增强现实解决方案及VR虚拟现实解决方案，为用户提供多方位服务。包括地产、家装、科研、展厅、营销、工业、教育、巡检远程指导，旅游等行业。
    -
      image: ./images/banner-01.jpg
      name: 云计算基础架构搭建
      description: 为数据中心、云计算、企业 IT、大型数据、HPC 和嵌入式市场开发并提供端到端的绿色计算解决方案。我们的模组化构建式解决方案允许我们提供范围广泛的 SKU, 并使我们能够根据您的需求构建和交付应用程序优化的解决方案。
    -
      image: ./images/banner-01.jpg
      name: 系统集成
      description: index.services[1].description
    -
      image: ./images/banner-01.jpg
      name: IDC机房
      description: index.services[0].description
    -
      image: ./images/banner-01.jpg
      name: 桌面化办公设备
      description: 供应品牌PC、兼容PC、办公设备（打印机、复印机、扫描仪）

  # 产品
  products:
    -
      image: ./images/banner-01.jpg
      name: VR行业解决方案
      description: index.products[0].description
    -
      image: ./images/banner-01.jpg
      name: 云计算基础架构搭建
      description: index.products[1].description
    -
      image: ./images/banner-01.jpg
      name: 系统集成
      description: index.products[2].description
    -
      image: ./images/banner-01.jpg
      name: IDC机房
      description: index.products[2].description
    -
      image: ./images/banner-01.jpg
      name: 桌面化办公设备
      description: 供应品牌PC、兼容PC、办公设备（打印机、复印机、扫描仪）

  # 案例
  cases:
    -
      image: ./images/banner-01.jpg
      name: ""
      description: index.cases[0].description
    -
      image: ./images/banner-01.jpg
      name: ""
      description: index.cases[1].description
    -
      image: ./images/banner-01.jpg
      name: ""
      description: index.cases[2].description
    -
      image: ./images/banner-01.jpg
      name: ""
      description: index.cases[3].description
    -
      image: ./images/banner-01.jpg
      name: ""
      description: index.cases[4].description
    -
      image: ./images/banner-01.jpg
      name: ""
      description: index.cases[5].description
    -
      image: ./images/banner-01.jpg
      name: ""
      description: index.cases[6].description
    -
      image: ./images/banner-01.jpg
      name: ""
      description: index.cases[7].description

# -----------------
# 关于页内容 about content
# -----------------

about:
    topSlogans:
      -
        image:
        title:
        description:
      - 
        image:
        title:
        description:
      -
        image:
        title:
        description:

  
# -----------------
# 页脚 footer
# -----------------

footer:
  about: 
    title: 关于宽恒
    items: 
    - 我们是谁: /link1/
    - 我们的客户: /link2/
    - 联系方式: /link3/
  
  product:
    title: 产品库
    items:
    - VR设备: /link1/
    - IDC: /link2/
    - 系统集成: /link3/
    - 桌面虚拟化: /link4/
      
  service: 
    title: 解决方案
    items:
    - 网络安全方案: /link1/
    - IDC机房方案: /link2/    
    - VR解决方案: /link3/
    - 系统服务方案: /link4/
    - 桌面维护方案: /link5/

  case:
    title: 成功案列
    items:
    - link1: /link1/
    - link2: /link2/
  
  update:
    title: 企业动态
    items:
    - link1: /link1/

  contact:
    title: 联系我们
    items:
    - 微信: wechatID
    - 电话: telno
  
since: 2019