# -----------------
# 企业信息 corp info
# -----------------

corp:
  name: 宽恒
  nameEnglish: Kuanheng
  about: 关于宽恒
  serices: 宽恒服务
  products: 宽恒产品
  samples: 成功案例

# -----------------
# 导航栏 navbar
# -----------------

nav:
  banner:
    - 
      banner: ./images/banner-01.jpg
      slogan: VR解决方案
      description: 填写你需要的简介
    - 
      banner: ./images/banner-02.jpg
      slogan: IDC机房
      description: 填写你需要的简介内容
    - 
      banner: ./images/banner-03.jpg
      slogan: 系统集成
      description: 填写你需要的简介内容目标
    -
      banner: ./images/banner-04.jpg
      slogan: 办公室设备
      description: 这里放置简介

# -----------------
# 菜单 menu
# -----------------

menu:
 首页: /
 关于宽恒: /about
 产品库: /product
 解决方案: /solution
 成功案例: /case
 企业动态: /update

tele: 400-008-0408

# -----------------
# 简要介绍 mini description
# -----------------


# -----------------
# 板式设定 layout
# -----------------

layout:
  about:
    name: about
  solution:
    name: solution
  case:
    name: case

# -----------------
# 主页内容 index content
# -----------------



# -----------------
# 关于页内容 about content
# -----------------

about:
    topSlogans:
      -
        image:
        title:
        description:
      - 
        image:
        title:
        description:
      -
        image:
        title:
        description:

  
# -----------------
# 页脚 footer
# -----------------

footer:
  about: 
    title: 关于宽恒
    items: 
    - 我们是谁: /link1/
    - 我们的客户: /link2/
    - 联系方式: /link3/
  
  product:
    title: 产品库
    items:
    - VR设备: /link1/
    - IDC: /link2/
    - 系统集成: /link3/
    - 桌面虚拟化: /link4/
      
  service: 
    title: 解决方案
    items:
    - 网络安全方案: /link1/
    - IDC机房方案: /link2/    
    - VR解决方案: /link3/
    - 系统服务方案: /link4/
    - 桌面维护方案: /link5/

  case:
    title: 成功案列
    items:
    - link1: /link1/
    - link2: /link2/
  
  update:
    title: 企业动态
    items:
    - link1: /link1/

  contact:
    title: 联系我们
    items:
    - 微信: wechatID
    - 电话: telno
  

footerInfo:
  corpname: 
  